config/routes.rb
Rails.application.routes.draw do
  resources :trump_tweets, only: [:index, :show]
  resources :markovs, only: [:index, :show]
  root 'markovs#index'

end

app/models/concerns/markovs_importer.rb
module MarkovsImporter

  def increment_markov_from_score(markov, score)
    score[:frequency] = 1
    score.each_pair do |tone, points|
      score[tone] = points + markov.read_attribute(tone)
    end
    return score
  end # increment_markov_from_score

  def calculate_score_from_tones(tones)
    defaults = Hash.new(0)
    tones.each do |tone|
      defaults[tone.id] =
        case
        when tone.score > 0.75
          2
        when tone.score > 0.5
          1
        else
          0
        end
    end
    return defaults
  end # calculate_score_from_tones

  def import_from_twitter
    tweets = TrumpTweet.oldest.unparsed.popular.limit(20)
    if tweets.length == 0
      STDERR.puts "There are no unparsed tweets downloaded to process. Aborting."
      return
    end
    while( tweets.length > 0 ) do
      ids = tweets.pluck(:id)
      TrumpTweet.where(id: ids).update_all(parsed: true)
      # hand 20 tweets off to Watson via Helios
      # get back the sentence analysis
      response = Helios::Bot::ToneAnalyzer_2017.tone( tweets.map(&:text).join("\n") )
      # walk the sentence, from beginning to end
      # each beginning node should be:
      #   Markov.new(current: nil, next: string)
      # each end of a sentence should be:
      #   Markov.new(current: string, next: nil)
      # NOTE: periods should be removed,
      #       only used at the end of a sentence
      response.sentences_tone.each do |sentence_tone|
        sentence_arr = sentence_tone.text.split
        break if sentence_arr.length == 0
        mc           = Markov.find_or_create_by(current: nil, next: sentence_arr[0])
        scores       = calculate_score_from_tones(sentence_tone.tones)
        updates_hash = increment_markov_from_score(mc, scores)
        mc.update(updates_hash)

        sentence_tone.text.split.each_cons(2) do |current_str, next_str|
          mc           = Markov.find_or_create_by(current: current_str, next: next_str)
          scores       = calculate_score_from_tones(sentence_tone.tones)
          updates_hash = increment_markov_from_score(mc, scores)
          mc.update(updates_hash)
        end # each word pair

        mc           = Markov.find_or_create_by(current: sentence_arr[-1], next: nil)
        scores       = calculate_score_from_tones(sentence_tone.tones)
        updates_hash = increment_markov_from_score(mc, scores)
        mc.update(updates_hash)

      end # sentence_tone
      # queue up more tweets
      tweets = TrumpTweet.oldest.unparsed.popular.limit(20)
    end # while
  end # import_from_twitter
end # module MarkovsImporter

app/models/concerns/trump_tweets_importer.rb
module TrumpTweetsImporter
  def import_from_twitter
    old_logger = ActiveRecord::Base.logger
    ActiveRecord::Base.logger = nil    
    print "Collecting @realDonaldTrump tweets: "
    lowest_id          = nil
    # first, see if there are any new tweets
    loop do
      options = {
        include_rts: false,
        tweet_mode: :extended,
        trim_user: true,
        count: 100
      }
      options[:max_id] = lowest_id if lowest_id

      tweets = Rails.application.config.twitter_client.user_timeline("realDonaldTrump", options)

      break if tweets.length == 0

      print '#'

      TrumpTweet.transaction do
        tweets.each do |tweet|
          attrs = tweet.attrs
          if TrumpTweet.exists?(id: attrs[:id])
            # we've seen this tweet before, so we're done
            break
          end
          # this is a new tweet to record
          TrumpTweet.create(
            id: attrs[:id],
            parsed: false,
            retweets: tweet.retweet_count,
            published_at: attrs[:created_at],
            text: attrs[:full_text]
          )
        end # each tweet
      end # transaction
      lowest_id = tweets.map{ |t| t.attrs[:id] }.min
    end # loop
  ensure
    ActiveRecord::Base.logger = old_logger
  end # import_from_twitter
end

app/models/markov.rb
class Markov < ActiveRecord::Base
  extend MarkovsImporter
end

app/models/trump_tweet.rb
class TrumpTweet < ActiveRecord::Base
  extend TrumpTweetsImporter

  scope :popular,  -> { where('"trump_tweets"."retweets" > 20000') }
  scope :unparsed, -> { where(parsed: false) }
  scope :oldest,   -> { order(:id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/markovs_controller.rb
class MarkovsController < ApplicationController
  before_action :set_markov, only: :show

  # GET /markovs
  # GET /markovs.json
  def index
    @markovs = Markov.all
  end

  # GET /markovs/1
  # GET /markovs/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_markov
      @markov = Markov.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def markov_params
      params.require(:markov)
    end
end

app/controllers/trump_tweets_controller.rb
class TrumpTweetsController < ApplicationController
  before_action :set_trump_tweet, only: :show

  # GET /trump_tweets
  # GET /trump_tweets.json
  def index
    @trump_tweets = TrumpTweet.all
  end

  # GET /trump_tweets/1
  # GET /trump_tweets/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trump_tweet
      @trump_tweet = TrumpTweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trump_tweet_params
      params.require(:trump_tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markovs_helper.rb
module MarkovsHelper
  def test_twitter
    tweets = Rails.application.config.twitter_client.user_timeline(
      "realDonaldTrump",
      include_rts: false,
      tweet_mode: :extended
    )

    tweets[1].attrs.each do |key, value|
      puts "#{key}:\t#{value}"
    end
    puts
    tweets.map do |tweet| puts tweet.attrs[:id] end
    puts
  end # test_twitter

  module_function :test_twitter
end

app/helpers/trump_tweets_helper.rb
module TrumpTweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DonaldTwitterBot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/markovs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Markovs</h1>

<table class="table table-stripped">
  <thead class="thead-light">
    <tr>
      <th>Current</th>
      <th>Next</th>
      <th>Frequency</th>
      <th>Recent</th>
      <th>Anger</th>
      <th>Fear</th>
      <th>Joy</th>
      <th>Sadness</th>
      <th>Analytical</th>
      <th>Confident</th>
      <th>Tentative</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @markovs.each do |markov| %>
      <tr>
        <td><%= markov.current %></td>
        <td><%= markov.next %></td>
        <td><%= markov.frequency %></td>
        <td><%= markov.recent %></td>
        <td><%= markov.anger %></td>
        <td><%= markov.fear %></td>
        <td><%= markov.joy %></td>
        <td><%= markov.sadness %></td>
        <td><%= markov.analytical %></td>
        <td><%= markov.confident %></td>
        <td><%= markov.tentative %></td>
        <td><%= link_to 'Show', markov %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/markovs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', markovs_path %>

app/views/trump_tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trump Tweets</h1>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Parsed</th>
      <th>Retweets</th>
      <th>Published at</th>
      <th>Text</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trump_tweets.each do |trump_tweet| %>
      <tr>
        <td><%= trump_tweet.parsed %></td>
        <td><%= trump_tweet.retweets %></td>
        <td><%= trump_tweet.published_at %></td>
        <td><%= truncate(trump_tweet.text) %></td>
        <td><%= link_to 'Show', trump_tweet %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trump_tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parsed:</strong>
  <%= @trump_tweet.parsed %>
</p>

<p>
  <strong>Retweets:</strong>
  <%= @trump_tweet.retweets %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @trump_tweet.published_at %>
</p>

<p>
  <strong>Text:</strong>
  <%= @trump_tweet.text %>
</p>

<%= link_to 'Back', trump_tweets_path %>